wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714359549.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.10.11
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
n_estimators:
  desc: null
  value: 100
max_depth:
  desc: null
  value: 12
min_samples_split:
  desc: null
  value: 3
min_samples_leaf:
  desc: null
  value: 3
